### PR TITLE
Added validations in signup form

### PR DESCRIPTION
**Pull request by mpvineesh**
- Removed number type from mobile number field
- Added angular email type validation
- Added number validation for mobile number field
- Added minlength validation for password fields

### CODE REVIEW

**Comment by kartikjagdale** [comment]
hi @mpvineesh Thanx for the PR, I really appreciate your effort.
Further, I reviewed the PR and tested the feature.
There are few things things that I noticed.
1. Even if the password doesn't match, it doesn't show error.
2. Mobile number input has a spin box which could be hidden.
cc: @ashish173

**Comment by mpvineesh** [comment]
Hi @kartikjagdale, I have added the password match validation. I couldn't see the spin box in mobile number input, I have tested  in Mozilla, Chrome and IE

**Comment by kartikjagdale** [comment]
hi @mpvineesh 
Thanx for the reply.
Actually I am testing in chrome and in chrome I can see the spin for number input.
For password match, the method works only once and not when a user does the changing of input value multiple times.
1. I suggest we implement a password validator directive rather than a method.
2. For hiding the spin box I suggest changing css properties of input box of type number.

**Comment by kartikjagdale** [comment]
@ashish173 
Tested and seems fine to me... we can merge this request.
@mpvineesh Thanx for the improvements.
:+1:

**Pull request merged**
